[2024-03-23T01:22:45.824+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_team_standings.add_to_table scheduled__2024-03-21T13:00:00+00:00 [queued]>
[2024-03-23T01:22:45.828+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_team_standings.add_to_table scheduled__2024-03-21T13:00:00+00:00 [queued]>
[2024-03-23T01:22:45.828+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 5
[2024-03-23T01:22:45.835+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): add_to_table> on 2024-03-21 13:00:00+00:00
[2024-03-23T01:22:45.838+0000] {standard_task_runner.py:60} INFO - Started process 524 to run task
[2024-03-23T01:22:45.841+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_team_standings', 'add_to_table', 'scheduled__2024-03-21T13:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/team_stats.py', '--cfg-path', '/tmp/tmp48qtkdks']
[2024-03-23T01:22:45.842+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask add_to_table
[2024-03-23T01:22:45.876+0000] {task_command.py:423} INFO - Running <TaskInstance: get_team_standings.add_to_table scheduled__2024-03-21T13:00:00+00:00 [running]> on host e4a45e6f747a
[2024-03-23T01:22:45.938+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jmc' AIRFLOW_CTX_DAG_ID='get_team_standings' AIRFLOW_CTX_TASK_ID='add_to_table' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-21T13:00:00+00:00'
[2024-03-23T01:22:45.945+0000] {base_aws.py:581} WARNING - Unable to find AWS Connection ID 'aws_default', switching to empty.
[2024-03-23T01:22:45.946+0000] {base_aws.py:161} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-03-23T01:22:45.976+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-03-23T01:22:47.151+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-03-23T01:22:47.207+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-23T01:22:47.216+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_team_standings, task_id=add_to_table, execution_date=20240321T130000, start_date=20240323T012245, end_date=20240323T012247
[2024-03-23T01:22:47.252+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-23T01:22:47.288+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
