[2024-03-23T01:27:22.516+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_team_standings.add_to_table scheduled__2024-03-21T13:00:00+00:00 [queued]>
[2024-03-23T01:27:22.521+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_team_standings.add_to_table scheduled__2024-03-21T13:00:00+00:00 [queued]>
[2024-03-23T01:27:22.521+0000] {taskinstance.py:2193} INFO - Starting attempt 6 of 7
[2024-03-23T01:27:22.528+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): add_to_table> on 2024-03-21 13:00:00+00:00
[2024-03-23T01:27:22.536+0000] {standard_task_runner.py:60} INFO - Started process 662 to run task
[2024-03-23T01:27:22.539+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_team_standings', 'add_to_table', 'scheduled__2024-03-21T13:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/team_stats.py', '--cfg-path', '/tmp/tmpn59je7dw']
[2024-03-23T01:27:22.541+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask add_to_table
[2024-03-23T01:27:22.576+0000] {task_command.py:423} INFO - Running <TaskInstance: get_team_standings.add_to_table scheduled__2024-03-21T13:00:00+00:00 [running]> on host e4a45e6f747a
[2024-03-23T01:27:22.637+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jmc' AIRFLOW_CTX_DAG_ID='get_team_standings' AIRFLOW_CTX_TASK_ID='add_to_table' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-21T13:00:00+00:00'
[2024-03-23T01:27:22.645+0000] {base_aws.py:581} WARNING - Unable to find AWS Connection ID 'aws_default', switching to empty.
[2024-03-23T01:27:22.646+0000] {base_aws.py:161} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-03-23T01:27:22.690+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-03-23T01:27:23.853+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-03-23T01:27:23.903+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-23T01:27:23.912+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_team_standings, task_id=add_to_table, execution_date=20240321T130000, start_date=20240323T012722, end_date=20240323T012723
[2024-03-23T01:27:23.972+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-23T01:27:24.002+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
